### ISSUE TITLE
Badge status always "pending" when Git dependency present

### ISSUE THREAD

**Issue by ssoloff** [alanshaw/david-www#368]
My David devDependency badge is always showing "pending" for one of [my projects](https://david-dm.org/ssoloff/dice-server-js/develop?type=dev) when I expect it to be "up to date" (yellow), based on the individual dependency statuses.  Below is a screenshot demonstrating this issue (just in case my dependency status changes by the time someone can take a look):

![david-dm-screenshot-with-pinned-git-version](https://cloud.githubusercontent.com/assets/4826349/23828990/61f10cb4-06b1-11e7-9d09-3f8f42ceb63a.png)

My theory is that `gulp-exclude-gitignore`'s Git dependency is causing the problem.  To test this theory, I changed the dependency to the latest published version and checked David's status for this branch:

![david-dm-screenshot-without-pinned-git-version](https://cloud.githubusercontent.com/assets/4826349/23829019/1bfb72d4-06b2-11e7-95b9-e86bbe168490.png)

Is the "pending" badge by design?  Or is it possible David has a problem generating the aggregate status when a Git dependency is present?

**Comment by gregswindle** [comment]
## Issue summary

One of my repositories -- [`gregswinde/generator-android-lib`](https://github.com/gregswindle/generator-android-lib/) -- has the same issue.


## Expected Behavior

The David-DM badge for [`gregswinde/generator-android-lib`](https://github.com/gregswindle/generator-android-lib/)'s dependencies should display display "dependencies | up to date" (in the green).

The badge for `gregswindle/generator-android-lib` displays correctly:

[![devDependencies Status](https://david-dm.org/gregswindle/generator-android-lib/dev-status.svg)](https://david-dm.org/gregswindle/generator-android-lib?type=dev)

## Current Behavior



The David-DM badge for [`gregswinde/generator-android-lib`](https://github.com/gregswindle/generator-android-lib/)'s dependencies displays as "pending," even though each package is "green" and up-to-date:

[![dependencies Status](https://david-dm.org/gregswindle/generator-android-lib/status.svg)](https://david-dm.org/gregswindle/generator-android-lib)

## Possible Solution



Unsure, sorry. :confused:

## Steps to Reproduce (for bugs)


1. Select the faulty badge for dependencies: [![dependencies Status](https://david-dm.org/gregswindle/generator-android-lib/status.svg)](https://david-dm.org/gregswindle/generator-android-lib)
2. Despite the badge's "pending" status, all dependencies are "up-to-date."

## Context



Like @alanshaw, my project has (three top-level) internal Git dependencies:

1. [git-remote-origin-url](https://www.npmjs.com/package/git-remote-origin-url): dependency
2. [github-usernam](https://www.npmjs.com/package/github-username): dependency
3. [git-labelmaker](https://www.npmjs.com/package/git-labelmaker): dev-dependency

Here are all nested packages (i.e., the output of `tree -d`):

[mac-osx-chrome-v57.0.2987.133-packages.tree.txt](https://github.com/alanshaw/david-www/files/956886/mac-osx-chrome-v57.0.2987.133-packages.tree.txt)

## Environment

### David-DM version: 
- v22.1.0
### Environment name and version:
- ua_type	Desktop
- os_name	macOS
- os_version	10.12.4
- browser_name	Chrome
- browser_version	57.0.2987.133
- engine_name	WebKit
- engine_version	537.36
### Operating System and version:
- ProductName:	Mac OS X (laptop)
- ProductVersion: 10.12.4
- BuildVersion:	16E195
### Link to your project: https://github.com/gregswindle/generator-android-lib

**Comment by alanshaw** [comment]
Thanks for your patients. I believe this bug has been resolved in by https://github.com/alanshaw/david-www/commit/6436f07bec18384d0d83a8e89b7fb40286da5bc8. Please comment if you notice this issue again.

**Comment by ssoloff** [comment]
Thanks for following up on this, @alanshaw!  I confirmed I no longer have a Pending dev dependency badge.  However, all of my badges now show as Up to Date (Green), when they should all be Up to Date (Yellow) based on the individual dependency statuses.  Is this just a caching issue (i.e. do I have to wait a bit longer)?  Or possibly a different problem?

**Comment by gregswindle** [comment]
Thanks, @alanshaw! It's working for me, now (as the badges in my [initial comment](https://github.com/alanshaw/david-www/issues/368#issuecomment-297201801) attest.

**Comment by ericmorand** [comment]
How can this issue be closed when it is visually obvious that it is not resolved?

* OP Package: ![](https://david-dm.org/gregswindle/generator-android-lib.svg?theme=shields.io)
* One of my own packages: ![](https://david-dm.org/ericmorand/stromboli-plugin-twig.svg?theme=shields.io)

**Comment by alanshaw** [comment]
Hi @ericmorand I'm just looking at this 11 minutes after you commented and your badges have already moved from pending to their appropriate states.

<img width="790" alt="screen shot 2017-06-14 at 10 09 38" src="https://user-images.githubusercontent.com/152863/27124676-be4ab88e-50e9-11e7-8844-d8950af04663.png">

**Comment by jeffminsungkim** [comment]
I'm having the exact same issue right now. I think this issue has to be reopened.

**Comment by alanshaw** [comment]
@jeffminsungkim can you point me to your `package.json`?

**Comment by jeffminsungkim** [comment]
@alanshaw Not sure why, but the issue has been resolved.

**Comment by johnnyBira** [comment]
Got the same issue:
https://david-dm.org/johnnyBira/responsive-props

**Comment by sangaman** [comment]
Same issue here: https://david-dm.org/sangaman/http-jsonrpc-server

**Comment by deepsweet** [comment]
Same [here](https://david-dm.org/deepsweet/start?path=packages%2Fplugin-lib-eslint), [`package.json`](https://github.com/deepsweet/start/blob/master/packages/plugin-lib-eslint/package.json).

**Comment by MrWook** [comment]
Same [here](https://david-dm.org/MrWook/mw-alert?type=dev)

**Comment by Borewit** [comment]
Same: 
* [here](https://david-dm.org/Borewit/then-read-stream), monitoring [then-read-stream](https://github.com/Borewit/then-read-stream)
* [and here](https://david-dm.org/Borewit/strtok2), monitoring [strtok2](https://github.com/Borewit/strtok2)

**Comment by dnl1** [comment]
Same [https://david-dm.org/dnl1/league-of-legends-api](here)

**Comment by ralego75** [comment]
Same [here](https://david-dm.org/ralego75/swagger-ui-http), [package.json](https://github.com/ralego75/swagger-ui-http/blob/master/package.json)

**Comment by s-herbert** [comment]
Samesies.
21 Dependencies total
 21 Up to date 
0 Pinned, out of date 
0 Out of date

yet,
"Pending"

**Comment by ralego75** [comment]
![image](https://user-images.githubusercontent.com/13320136/46610562-625ad980-cb0b-11e8-9ebe-0e80eaf6d48a.png)
Yet pending ...

**Comment by alanshaw** [comment]
<img width="775" alt="screenshot 2018-11-16 at 16 40 29" src="https://user-images.githubusercontent.com/152863/48634782-58f04700-e9be-11e8-96a2-5cc51df82f6a.png">

looks good to me...

**Comment by jfoclpf** [comment]
Didn't want to bother, but do you know how much time does it take to process? It's been 30 minutes already since I gave permissions and signup
<img src="https://david-dm.org/jfoclpf/autocosts.svg"/>

In any case I read the disclaimer :) 

>David is currently BETA, which means it may be unreliable, unavailable or not working. That said, it's already useful and we're working to make it rock solid.

Thanks for the cool plugin

**Comment by chrisweb** [comment]
[![dependencies Status](https://david-dm.org/chrisweb/web-audio-api-player/status.svg)](https://david-dm.org/chrisweb/web-audio-api-player)

problem seems to be back (>24h since update)

**Comment by Borewit** [comment]
@alanshaw, can you please re-open?
Issue is clearly not solved, still lots of gray badge icons.

**Comment by dangen-effy** [comment]
same [here](https://david-dm.org/dangen-effy/joi-mongoose-indexes)
